### ISSUE TITLE
CucumberExtentReporter

### ISSUE THREAD

**Issue by email2vimalraj** [sitture/cucumber-jvm-extentreport#1]
@haroon-sheikh : I'm just wondering how it is different from this library: https://github.com/email2vimalraj/CucumberExtentReporter

I'm the author of the above library and yours almost looking like mine even the code. Just wanted to ensure that whether you are aware of my library or not.

**Comment by haroon-sheikh** [comment]
@email2vimalraj It's a fork of your library (mentioned here https://github.com/sitture/cucumber-jvm-extentreport/releases) with just minor modifications that we're using here.

**Comment by haroon-sheikh** [comment]
I'm currently looking at making it work when using cucumber cli within gradle. I wouldn't mind us merging, as long as long we're both happy with the changes.
