### ISSUE TITLE
Upgrade to use cucumber-jvm v2

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/cucumber-jvm-extentreport#7]

**Comment by jreijn** [comment]
I would like to help with this.

**Comment by haroon-sheikh** [comment]
Thanks @jreijn. Please go ahead submit a PR.

**Comment by jreijn** [comment]
@haroon-sheikh I was thinking of swithing the report style to use the BDD style like mentioned in: [Extent BDD](http://extentreports.com/samples/extent-bdd.html#!) What do you think about that?

**Comment by haroon-sheikh** [comment]
It’s sound good @jreijn. Go for it.

**Comment by jreijn** [comment]
I've created pull request #12 for this.
