### ISSUE TITLE
Add a Maven+Cucumber example project.

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/cucumber-jvm-extentreport#8]

**Comment by joergsesterhenn** [comment]
I'd like to do this. What exactly should the example show?

**Comment by haroon-sheikh** [comment]
@joergsesterhenn A simplest cucumber-jvm project making use of this formatter that exports the test results into extentreport.

**Comment by joergsesterhenn** [comment]
Please have a look at my PR. Btw. your Maven snippet for importing the project has an extra 's' that does not belong 
```
<dependency>
    <groupId>com.sitture</groupId>
    <artifactId>cucumber-jvm-extentsreport</artifactId>
<!--                               ^   -->
    <version>2.0.0</version>
</dependency>
```

**Comment by haroon-sheikh** [comment]
Thanks @joergsesterhenn
